### ISSUE TITLE
Using Lassotool as mouse-shortcut

### ISSUE THREAD

**Issue by DaGeggo** [Marian-Braendle/ipe-lassotool#1]
This is a nice tool, thanks a lot! 
Intuitively, I'd like to use the lasso select when pressing STRG and then start selecting with the mouse (I think, this is how other applications do this). I tried to do it myself, but haven't been successful, as I never used lua nor did I do something like this. 

Have you tried this already or do you have an idea, how to add this?

**Comment by Marian-Braendle** [comment]
Hi DaGeggo,

I'm not sure if I've understood you correctly. In Ipe there is the possibility to add mouse bindings. For example, you can create a binding for CTRL+Left Mouse.
Without modifying the existing Ipelet you could write the following:
```lua
mouse.left_control = function (model, modifiers)
    tool = LASSOTOOL:new(model)
    tool:mouseButton(1, modifiers, true)
end
```

This way CTRL+Left Mouse would always start the lasso tool. By the way, this key binding is global and not just limited to the selection tool, for example. 

I hope this was helpful 😉

**Comment by DaGeggo** [comment]
Oh yeah, that does the trick. Thank you!
